export const mockNotes = [
  {
    _id: '2',
    text: 'Note text',
    title: 'Note title',
    list: [],
    drawing: '',
    drawingImage: '',
    recording: '',
    recordingDuration: '',
    image: '',
    isPinned: false,
    userGoogleId: '123',
    lastEdited: 789,
  },
  {
    _id: '3',
    text: '',
    title: '',
    list: [
      { text: 'first item', done: true, id: '123' },
      { text: 'second item', done: false, id: '456' },
    ],
    drawing: '',
    drawingImage: '',
    recording: '',
    recordingDuration: '',
    image: '',
    isPinned: false,
    userGoogleId: '123',
    lastEdited: 123,
  },
  {
    _id: '4',
    text: '',
    title: '',
    list: [],
    drawing: 'sdfhsfghsfghsh',
    drawingImage: 'sfghsfgdhsdfhsdfh',
    recording: '',
    recordingDuration: '',
    image: '',
    isPinned: false,
    userGoogleId: '123',
    lastEdited: 123,
  },
  {
    _id: '5',
    text: '',
    title: '',
    list: [],
    drawing: '',
    drawingImage: '',
    recording: 'srthsdfhsdfhsdhf',
    recordingDuration: '0:0:12',
    image: '',
    isPinned: true,
    userGoogleId: '123',
    lastEdited: 123,
  },
  {
    _id: '6',
    text: '',
    title: '',
    list: [],
    drawing: '',
    drawingImage: '',
    recording: '',
    recordingDuration: '',
    image: 'gdfhfdhsfdhsdfhsdfhsfdh',
    isPinned: true,
    userGoogleId: '123',
    lastEdited: 123,
  },
]
